### ISSUE TITLE
Reinventing the wheel

### ISSUE THREAD

**Issue by ensisnoctis** [tailscale/hujson#1]
JSON + human readability + comments + smaller file sizes = YAML
Try it ;)

**Comment by apenwarr** [comment]
You forgot "+ turing complete". yaml goes way too far.

**Comment by jrencz** [comment]
https://json5.org also addresses the issues

**Comment by crawshaw** [comment]
I originally looked into json5. It suffers the usual fate of standard extensions, in that it adds more than is strictly necessary to solve the problem. Still, if it were widely used and had developed all the Go tooling I would expect of a widely used standard, I would have gone with it. But it doesn't, so it was easier to spend a couple days doing this.

Long-term, if the contents of our configuration files stabilizes and we are confident it won't change, we may come up a custom format to represent it.

**Comment by rogpeppe** [comment]
FWIW there's also https://github.com/rogpeppe/rjson.

**Comment by rogpeppe** [comment]
These days, I'm actually a fan of Cue's syntax. If you use a strictly concrete subset, I think that could make a great JSON-alternative. I think it could be worth doing that as a standalone thing.

**Comment by frioux** [comment]
I'm excited to use this; a simple config format that I already know the semantics of with a few basic improvements.  ++

**Comment by FyiurAmron** [comment]
obligatory xkcd: https://xkcd.com/927/

**Comment by NuSkooler** [comment]
Or HJSON which already covers this and has the name...

**Comment by bradfitz** [comment]
[HSON](https://hjson.github.io/) goes too far, IMO. YAML also went that path where they just kept adding stuff.

`tailscale/hujson` is JSON + comments. Not multiline strings, omitting commas, omitting quotes, etc. At a certain point it gets hard to even recognize it as JSON.

**Comment by FyiurAmron** [comment]
obligatory xkcd: https://xkcd.com/927/
