### ISSUE TITLE
How to update parsed hujson's Value?

### ISSUE THREAD

**Issue by mohsenari** [tailscale/hujson#27]
I've been testing hujson and trying to read, edit, then write the edited data back to my json file. But I can't find an example in the docs or the source code on how to write back an edited object while preserving the commas and comments. Note the `jwcc.Value = ???` in my example code:

test.json
```json
{
  "foo": "bar" // some comment
}
```
main.go
```go
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/tailscale/hujson"
)

func main() {
	fileBytes, err := os.ReadFile("test.json")
	if err != nil {
		fmt.Printf("error reading file: %s", err)
	}
	// read json with commas and comments
	jwccData, err := hujson.Parse(fileBytes)

	// get standard json data into tst
	tst := &test{}
	standardData, err := hujson.Standardize(fileData)
	json.Unmarshal(standardData, tst)

	// update standard data
	tst.Foo = "bar-moodified"

	// TODO: HOW to put the updated tst as jwccData.Value 
	jwcc.Value = ???

	// write the updated tst data back to test.json
	os.WriteFile("test-updated.json", preservedJSON.Pack(), 0644)

	fmt.Println("Preserved JSON Data updated")
	fmt.Println(preservedJSON)
}

type test struct {
	Foo string `json:"foo"`
}


```

**Comment by dsnet** [comment]
There isn't a way to automatically correlate changes to a Go data structure with the original HuJSON input. That is a hard problem since unmarshaling a JSON input into Go and then marshaling it back to JSON very rarely produces the exact output.

For small and surgical changes, you can do something like:
```go
if v := jwccData.Find("/foo"); v != nil {
    v.Value = hujson.String("bar-moodified")
}
```

**Comment by dsnet** [comment]
Closing as non-actionable.
