### ISSUE TITLE
update for go1.14

### ISSUE THREAD

**Issue by crawshaw** [tailscale/hujson#3]
The base of hujson is go1.13, the specific commit number is in https://github.com/tailscale/hujson/commit/e2a9696a57f84acb1a0b2d50b986b180be9ed8c4. We should git diff `go/src/pkg/encoding/json` between that commit and go1.14 and apply the diff to hujson.

**Comment by apenwarr** [comment]
('git-subtree split' might be useful for keeping up with the history of
go/src/pkg/encoding/json. Then we could rebase our patches on top.)

**Comment by bradfitz** [comment]
"update for go1.14" 😂 

(we now use Go 1.18)

**Comment by dsnet** [comment]
It doesn't really matter anymore since we dont use a fork of `encoding/json` anymore.
