### ISSUE TITLE
RFC 8785 JSON Canonicalization support

### ISSUE THREAD

**Issue by tonyhb** [tailscale/hujson#32]
Thoughts on implementing RFC 8785 support when formatting via Standardize, or add another `Canonicalize()` method which does the same thing?

**Comment by bradfitz** [comment]
For others,

JSON Canonicalization Scheme (JCS)
https://www.rfc-editor.org/rfc/rfc8785

**Comment by dsnet** [comment]
RFC 8785 depends on a non-trivial sorting order for object keys and a non-trivial formatting for floating-point numbers. It may be out of scope for the `hujson` package to provide an implementation for this.

If you need canonical formatting, you can do:
```go
import (
    "github.com/tailscale/hujson"
    "github.com/go-json-experiment/json"
)

b, err := hujson.Standardize(b)
if err != nil {
   log.Fatal(err)
}
if err := (*json.RawValue)(&b).Canonicalize(); err != nil {
    log.Fatal(err)
}
```

**Comment by tonyhb** [comment]
Noted — was only curious because this package has clean code and figured it was relative.  We have some stuff for this already;  appreciate the thoughts! 🙏
